server:
  port: 2333

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.5"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "hylous1234@lava"

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      http: true
      twitch: true
      vimeo: true
      local: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID
      - TVHTML5EMBEDDED

logging:
  level:
    root: INFO
    lavalink: INFO
